### ISSUE TITLE
Unsized imports array in wasm_instance_new.

### ISSUE THREAD

**Issue by peterhuene** [WebAssembly/wasm-c-api#104]
Currently `wasm_instance_new` has the signature:

```c
own wasm_instance_t* wasm_instance_new(
  wasm_store_t*,
  const wasm_module_t*,
  const wasm_extern_t* const imports[],
  own wasm_trap_t**
);
```

The `imports` array is unsized (i.e. there is no corresponding parameter to denote the length of the array).  This means that if the length of the imports for the module being instantiated does not match the length of the given imports array, a runtime has no way of failing the instantiation other than undefined behavior (e.g. a segfault).

A runtime needs to blindly index into the `imports` parameter based on the imports in the module being instantiated.  If an `imports_length` parameter were added to `wasm_instance_new`, a runtime would be able to detect the mismatch and potentially return a trap result instead of invoking undefined behavior.

Alternatively, `wasm_module_imports` could be called to get the module's imports and ensure the count is correct prior to instantiating, but it's likely pretty easy for the runtime implementation to check the internal representation of the module's import length against a parameter than forcing users of the C API to alloc a vec of imports just to perform this check.

**Comment by rossberg** [comment]
The length is given by the module parameter. Both the caller and the callee of course need to be aware of the import signature of the module. There is no scenario in which one can reasonably call this function without knowing what the module imports are, *both* their number and their types. So a caller usually has to look up wasm_module_imports anyway.

The fact that a caller violating a function's contract can lead to undefined behaviour in the callee is standard situation in C. Duplicating information in the parameter list does not change that, it merely creates redundant work for both sides to provide/check it.

**Comment by peterhuene** [comment]
That's a fair expectation (namely that the imports would need to be resolved anyway prior to instantiation), so it's unlikely that there would be a mismatch in normal usage. And providing a length can't prevent undefined behavior anyway (correct length, incorrectly allocated array for example), so I agree it's redundant even if it doesn't initially appear so when examining the function signature.

I'll close this issue as won't fix. Thanks!
