### ISSUE TITLE
Unconditional move of forwarding reference

### ISSUE THREAD

**Issue by TartanLlama** [WebAssembly/wasm-c-api#117]
In [`vec::make`](https://github.com/WebAssembly/wasm-c-api/blob/master/include/wasm.hh#L161):

```
  template<class... Ts>
  static auto make(Ts&&... args) -> vec {
    T data[] = { std::move(args)... };
    return make(sizeof...(Ts), data);
  }
```

The `std::move(args)...` should be `std::forward<Args>(args)...`, otherwise it will move from non-const lvalue reference arguments.

**Comment by rossberg** [comment]
Closed by #120.
