### ISSUE TITLE
Problems with the C API header

### ISSUE THREAD

**Issue by DagAgren** [WebAssembly/wasm-c-api#154]
Some of the function defines, like `WASM_API_EXTERN own wasm_config_t* wasm_config_new();` are not quite correct, and should use (void) for the arguments. () works, but defines a function with undeclared arguments, rather than one with no arguments. Xcode, at least, will by default warn on this:

    .../wasm.h:121:51: This function declaration is not a prototype

**Comment by rossberg** [comment]
Ah, good point. Old C++ habits, which clang doesn't warn about by default. Would you be interested in creating a PR? :)
