### ISSUE TITLE
Syslog

### ISSUE THREAD

**Issue by Sebgg** [WebAssembly/wasm-c-api#167]
Hello!

Is there any way to include syslog.h in a c-program that will compile to Wasm/WASI at the moment?

**Comment by Hywan** [comment]
Hello,

Thank you for your question. Unfortunately this repository doesn't aim at providing support for Wasm or WASI for C :-). My best advice is: Try! If it doesn't compile or doesn't run correctly, take a look at [`wasi-libc`](https://github.com/WebAssembly/wasi-libc), `clang`, or [`wasienv`](https://github.com/wasienv/wasienv).

**Comment by Sebgg** [comment]
Thanks for the answer!
