### ISSUE TITLE
How to import a native func to "env"?

### ISSUE THREAD

**Issue by MrHate** [WebAssembly/wasm-c-api#191]
I'm new to this wasm-c-api but I couldn't find any doc or example about it.
I'm trying some wasm applications that import native functions from the env 'env' (commonly compiled with emcc), what is a correct way to achieve this with the wasm-c-api interface?

**Comment by rossberg** [comment]
You can find various examples in the `example/` directory of this repo. In particular, the `callback` example shows how to create a host function and provide that as an import.

The other half of your question seems to be how to populate the "env" import of Emscripten-compiled code. That is merely a naming convention used by Emscripten. On the raw Wasm level it simply amounts to imports whose module name is "env". However, in the C API, import names are irrelevant. You simply provide the imports to a module as a vector of extern values in the order declared by that module.

**Comment by MrHate** [comment]
Thanks a lot for replying, but sorry I don't follow you.

> However, in the C API, import names are irrelevant. You simply provide the imports to a module as a vector of extern values in the order declared by that module.

Is this impossible to achieve or any feasible way with specific code as example?
I've checked the examples in the `example/` dir but none enlightens me.
