### ISSUE TITLE
What are Foreigns good for?

### ISSUE THREAD

**Issue by jakobkummerow** [WebAssembly/wasm-c-api#67]
The current definition of `Foreign` seems very minimal:

```
class Foreign : public Ref {
public:
  Foreign() = delete;
  ~Foreign();

  static auto make(Store*) -> own<Foreign*>;
  auto copy() const -> own<Foreign*>;
};
```

And there are no examples using them. What are they useful for? Are they supposed to wrap a value of some sort? Are they a work in progress and will be expanded later?

**Comment by rossberg** [comment]
This provides a way to create host references. You can attach data by setting host info on the reference.

**Comment by jakobkummerow** [comment]
Ah, I had overlooked the inherited `set_host_info` path. Still, it would be nice to have an example using `Foreign` :-)
