### ISSUE TITLE
Add option to configure garbage collection on VM shutdown.

### ISSUE THREAD

**Issue by PiotrSikora** [WebAssembly/wasm-c-api#74]
Please add an option to configure garbage collection on VM shutdown at the API level, separately from `#ifdef DEBUG`.

Currently, garbage collection in V8 is forced to run in `~StoreImpl()` only when built with `-DDEBUG`, and leaks memory otherwise. Ideally, it should always run, to avoid any memory leaks, but I understand that this is waste of CPU cycles if the process is going to be terminated anyway.

This could be exposed in the API as:
```
Store(bool fast_shutdown = false);
```

cc @jakobkummerow @rossberg

**Comment by jakobkummerow** [comment]
I'm supportive of this request, and have no implementation concerns.

While the current motivation is V8-specific (given that V8 is currently the only (known?) implementation of this API), I assume that many/most future implementations might have a sufficient amount of internal state per `Store` that a distinction between "clean it up properly, the process is going to live on and I don't want memory leaks" and "just terminate as fast as possible, the process is going to quit anyway" has some benefit.

**Comment by rossberg** [comment]
AFAICT, destroying a V8 isolate (which is what a store corresponds to) frees all its memory, so there shouldn't be any leak. The debug code there only does it explicitly so that it can report what references are still left at that point (i.e., have leaked in user code, not on the engine level).

**Comment by rossberg** [comment]
@jakobkummerow, I think @PiotrSikora's request is the inverse direction. However, it may be based on a misunderstanding of the current behaviour.

**Comment by jakobkummerow** [comment]
Destroying the `Isolate` frees all memory on the heap, but any `HostData` objects waiting for finalization callbacks will stick around (and, hence, leak).

I suppose as an alternative we could solve that with additional bookkeeping. Or just make the GC-on-shutdown behavior the default, if it's undesirable to have an opt-in fast path for cases where the embedder doesn't care about cleanup.

**Comment by rossberg** [comment]
Ah, okay, I see. Yes, leaking HostData is undesirable behaviour.

Additional bookkeeping would probably impose notable cost on all uses of host data. More efficient would be a custom "shutdown heap walker" that doesn't do all the extra work needed for actual GC.

Does forcing a single major collection even guarantee that all weak data is finalised?

**Comment by PiotrSikora** [comment]
Yeah, I don't really care about actual GC, but I want to stop leaking the HostData in wasm-c-api itself, and running GC seems to achieve that.

No idea if running GC is guaranteed to finalize all weak data, but it seems to work fine in my limited testing. Any ideas, @jakobkummerow?

**Comment by jakobkummerow** [comment]
Yes, I have confirmed with the GC team that a GC cycle is enough to call the weak callbacks.

That said, I also think that that's an implementation detail, and it's up to implementations of the API to figure out a reliable mechanism. On the API level, the distinction shouldn't be "do GC or don't", but more generally "clean up properly or don't". Implementations can then decide whether they accomplish that by doing a GC cycle, or with additional bookkeeping, or through a lightweight finalizers-only GC cycle if available, etc.

**Comment by rossberg** [comment]
@jakobkummerow, agreed, but I was trying to figure out whether invoking GC is even sufficient as a stop-gap measure.

**Comment by jakobkummerow** [comment]
Yes, as I said, in V8's current implementation, invoking GC (and waiting for any posted tasks) is sufficient, so the current implementation can be assumed to be reliable.
