### ISSUE TITLE
Where are the source code of example/*.wasm?

### ISSUE THREAD

**Issue by mrpre** [WebAssembly/wasm-c-api#87]
I guess the `example/hello.c` is compiled to binary `out/example/hello-c` which is used to load  `out/example/hello.wasm`  and I guess the `hello-c` do some  interaction with `hello.wasm` such as `callback`.  

I'm trying to learn the c-api of this project but it's difficult for me to learn it without the source code of `example/*.wasm`.  
 For example I'm confused how the `hello.wasm` call the `hello_callback` defined in `hello.c`, should I need the source code ?

**Comment by rossberg** [comment]
The sources for the wasm files in the examples directory are the respective wat files.
