### ISSUE TITLE
Why -fsanitize=address is needed

### ISSUE THREAD

**Issue by mrpre** [WebAssembly/wasm-c-api#88]
I find I have to use `-fsanitize=address` when building this project otherwise some link error will be outputted like this :   
```
root/v8/wasm-c-api/src/wasm-c.cc:674: undefined reference to `__asan_report_load8'
/root/v8/wasm-c-api/src/wasm-c.cc:674: undefined reference to `__asan_report_load8'
```    

I have successfully embedded `wasm-c-api` into `Nginx` as a binary but `Nginx` does not clean memory it have already alloced if it tend to exit certainly like doing `-s reload`.   
Something error will be outputted like this:   

```
=================================================================
==585==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 1024 byte(s) in 1 object(s) allocated from:
    #0 0x7f304b9947a0 in posix_memalign (/usr/lib/x86_64-linux-gnu/libasan.so.4+0xdf7a0)
    #1 0x5651983ae4d0 in ngx_memalign src/os/unix/ngx_alloc.c:76

SUMMARY: AddressSanitizer: 1024 byte(s) leaked in 1 allocation(s).
```
All in all, how could I disable `-fsanitize=addres` ?  I think it's ungraceful output for some operation.

**Comment by rossberg** [comment]
It's a configurable part of the Makefile, so you can just remove it. It is not needed, just useful when running tests and experimenting.

**Comment by mrpre** [comment]
@rossberg ... I just removed it and did `make` then  some error like `undefined reference to `__asan_report_load8'` was outputted.    

I re-checkout a new  `wasm-c-api` project and remove `-fsanitize=address` before I do `make` then it works.  

Thanks.
